# NEOVIM PLUGINS SYNCHRONOUSLY LOADED


##
# dein
# :help dein
# https://github.com/Shougo/dein.vim

[[plugins]]
repo = 'Shougo/dein.vim'


##
# easymotion
# https://github.com/easymotion/vim-easymotion

[[plugins]]
repo = 'easymotion/vim-easymotion'


##
# neomru
# https://github.com/Shougo/neomru.vim

[[plugins]]
repo = 'Shougo/neomru.vim'


##
# neoyank
# https://github.com/Shougo/neoyank.vim

[[plugins]]
repo = 'Shougo/neoyank.vim'


##
# denite
# :help denite
# https://github.com/Shougo/denite.nvim

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
hook_add = '''
nnoremap <silent> <C-k><C-b> :<C-u>Denite buffer<CR>
nnoremap <silent> <C-k><C-f> :<C-u>Denite file_rec<CR>
nnoremap <silent> <C-k><C-g> :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>
nnoremap <silent> <C-k><C-r> :<C-u>Denite -resume -buffer-name=search-buffer-denite -select=+1<CR>
nnoremap <silent> <C-k><C-l> :<C-u>Denite line<CR>
nnoremap <silent> <C-k><C-u> :<C-u>Denite file_mru<CR>
nnoremap <silent> <C-k><C-y> :<C-u>Denite neoyank<CR>

call denite#custom#var('file_rec', 'command',
    \ ['pt', '--follow', '--nocolor', '--nogroup', '-g', ''])

call denite#custom#var('grep', 'command', ['pt'])
call denite#custom#var('grep', 'default_opts',
    \ ['--nogroup', '--nocolor', '--smart-case'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
'''


##
# neosnippet
# https://github.com/Shougo/neosnippet.vim

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
let g:neosnippet#snippets_directory = expand('$XDG_CONFIG_HOME/nvim/snippets/')
let g:neosnippet#enable_completed_snippet = 1
'''


##
# nvim-completion-manager
# https://github.com/roxma/nvim-completion-manager

[[plugins]]
repo = 'roxma/nvim-completion-manager'
depends = ['neosnippet']


##
# EditorConfig Vim Plugin
# https://github.com/editorconfig/editorconfig-vim

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
let g:EditorConfig_max_line_indicator = "line"
'''


##
# Vim colorschemes
# https://github.com/flazz/vim-colorschemes

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
set termguicolors
if has('gui_vimr')
    colorscheme editplus
else
    colorscheme Monokai
endif
'''


##
# Solarized
# https://github.com/frankier/neovim-colors-solarized-truecolor-only

[[plugins]]
repo = 'frankier/neovim-colors-solarized-truecolor-only'
hook_add = '''
"set termguicolors
"if has('gui_running')
"    set background=light
"else
"    set background=dark
"endif
"colorscheme solarized
'''


##
# NERDTree
# https://github.com/scrooloose/nerdtree

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
if !has('gui_vimr')
    let g:NERDTreeShowBookmarks=1
    autocmd VimEnter * NERDTree
    autocmd VimEnter * wincmd w
    autocmd BufEnter * NERDTreeMirror
endif
'''


##
# dispatch.vim
# https://github.com/tpope/vim-dispatch

[[plugins]]
repo = 'tpope/vim-dispatch'


##
# ALE
# https://github.com/w0rp/ale

[[plugins]]
repo = 'w0rp/ale'
depends = ['vim-virtualenv', 'vim-vue']
hook_add = '''
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

let g:airline#extensions#ale#enabled = 1
let g:ale_echo_msg_format = '[%linter%] %s'
let g:ale_fix_on_save = 1

let g:ale_linters = {
    \ 'css': ['stylelint'],
    \ 'html': [],
    \ 'javascript': ['eslint'],
    \ 'vue': ['stylelint', 'eslint'],
    \ }
let g:ale_linter_aliases = {'vue': ['css', 'html', 'javascript']}

let g:ale_fixers = {
    \ 'python': ['autopep8'],
    \ }
'''


##
# fugitive.vim
# https://github.com/tpope/vim-fugitive

[[plugins]]
repo = 'tpope/vim-fugitive'


##
# vim-airline
# https://github.com/vim-airline/vim-airline

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'vim-fugitive']
hook_add = '''
let g:airline_theme = 'solarized'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
'''
