# NEOVIM PLUGINS ASYNCHRONOUSLY LOADED


##
# vim-tags
# https://github.com/szw/vim-tags

[[plugins]]
repo = 'szw/vim-tags'
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
let g:vim_tags_auto_generate = 1
'''


[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'kongo2002/fsharp-vim'
on_ft = ['fs', 'fsi', 'fsx']

[[plugins]]
repo = 'OrangeT/vim-csharp'
on_ft = ['cs', 'csi', 'csx']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_add = '''
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_flow = 1
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'tikhomirov/vim-glsl'
on_ft = ['frag', 'vert']

[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['ps1']

[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']
