[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'aperezdc/vim-template'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'frankier/neovim-colors-solarized-truecolor-only'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'mtscout6/syntastic-local-eslint.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'easymotion/vim-easymotion'
