[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'kongo2002/fsharp-vim'
on_ft = ['fs', 'fsi', 'fsx']

[[plugins]]
repo = 'OrangeT/vim-csharp'
on_ft = ['cs', 'csi', 'csx']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htm']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js']

[[plugins]]
repo = 'kewah/vim-stylefmt'
on_ft = ['css']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'tikhomirov/vim-glsl'
on_ft = ['frag', 'vert']

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs', 'csi', 'csx']

  [plugins.build]
  windows = 'msbuild server/OmniSharp.sln'
  mac     = 'xbuild server/OmniSharp.sln'
  unix    = 'xbuild server/OmniSharp.sln'
