file_opener = "none"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
approval_policy = "never"
sandbox_mode = "workspace-write"
personality = "pragmatic"

[shell_environment_policy]
inherit = "all"

[features]
codex_hooks = true
multi_agent = true
js_repl = true

[mcp_servers.Asana]
url = "https://mcp.asana.com/v2/mcp"
enabled = false

[mcp_servers.ChromeDevtools]
command = "chrome-devtools-mcp"
args = []
enabled = false

[mcp_servers.Context7]
url = "https://mcp.context7.com/mcp"
http_headers = { "CONTEXT7_API_KEY" = "${CONTEXT7_API_KEY}" }

[mcp_servers.Figma]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.Filesystem]
command = "mcp-server-filesystem"
args = [
    "/Users",
]
enabled = false

[mcp_servers.Miro]
url = "https://mcp.miro.com/"
enabled = false

[mcp_servers.Notion]
url = "https://mcp.notion.com/mcp"
enabled = false

[mcp_servers.Playwright]
command = "playwright-mcp"
args = []
default_tools_approval_mode = "approve"

[mcp_servers.Serena]
command = "serena"
args = [
    "start-mcp-server",
]
default_tools_approval_mode = "approve"
disabled_tools = ["execute_shell_command"]

[sandbox_workspace_write]
network_access = true
writable_roots = ["/tmp", "~/.cache", "~/.codex/worktrees/", "~/.local", "~/.npm", "~/.serena"]
