file_opener = "none"
model = "gpt-5.5"
model_reasoning_effort = "high"
service_tier = "flex"
approval_policy = "never"
sandbox_mode = "workspace-write"
personality = "pragmatic"

[shell_environment_policy]
inherit = "all"

[features]
enable_mcp_apps = true
fast_mode = true
goals = true
hooks = true
js_repl = true
multi_agent = true

[mcp_servers.Asana]
url = "https://mcp.asana.com/v2/mcp"
enabled = false

[mcp_servers.ChromeDevtools]
command = "chrome-devtools-mcp"
args = []
enabled = false

[mcp_servers.Context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { "CONTEXT7_API_KEY" = "CONTEXT7_API_KEY" }

[mcp_servers.Figma]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.Filesystem]
command = "mcp-server-filesystem"
args = [
    "/Users",
]
enabled = false

[mcp_servers.Miro]
url = "https://mcp.miro.com/"
enabled = false

[mcp_servers.Notion]
url = "https://mcp.notion.com/mcp"
enabled = false

[mcp_servers.Playwright]
command = "playwright-mcp"
args = []
default_tools_approval_mode = "approve"

[mcp_servers.Serena]
command = "serena"
args = [
    "start-mcp-server",
]
default_tools_approval_mode = "approve"
disabled_tools = ["execute_shell_command"]

[sandbox_workspace_write]
network_access = true
writable_roots = [
    "/tmp",
    "~/.cache",
    "~/.codex/sessions",
    "~/.codex/worktrees",
    "~/.local",
    "~/.npm",
    "~/.portless",
    "~/.serena",
    "~/.yarn/berry/cache",
]

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[projects."/home/ubuntu/Workspace/com.github.japboy.dotfiles"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 1
