color = true
group = true
smart-case = true
ignore = [".git", ".venv", "__pycache__", "node_modules"]
vcs-ignore = [".gitignore"]
global-gitignore = false
home-ptignore = false
skip-vcs-ignores = true
